export enum ButtonName {
  Save = 'Save',
  Edit = 'Edit',
  Enable = 'Enable',
  Disable = 'Disable',
  Delete = 'Delete',
  Login = 'Login',
  Register = 'Register',
  VerifyOTP = 'Verify OTP',
  Next = 'Next',
  ResetPassword = 'Reset Password',
  ManageCast = 'Manage Cast',
  ManageMovies = 'Manage Movies',
  AddCast = 'Add Cast',
  AddMovie = 'Add Movie',
  Movies = 'Movies',
  Cast = 'Cast',
}
